## ---------------------------
## Script name: NEFSC_db_Connector.R
##
## Purpose of script: To simplify connection to NEFSC databases from within the
##  firewall. Users must supply connection information in a an encrypted .yml 
##  file generated by NEFSC_Config_Creator()
##
## Date Created: 2023-01-11
##
## Software code created by U.S. Government employees is 
## not subject to copyright in the United States 
## (17 U.S.C. §105).
##
## Email: george.maynard@noaa.gov
##
## ---------------------------
## Notes:
##   
##
## ---------------------------
NEFSC_db_Connector=function(){
  config_file=file.choose()
  encryptr::decrypt_file(config_file)
  config_filename=strsplit(config_file,"[\\]")[[1]][length(strsplit(config_file,"[\\]")[[1]])]
    db_config=config::get(file=paste0(
      strsplit(config_filename,"[.]")[[1]][1],
      ".yml"
    ))$config
  connect.string=paste0(
    "(DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=", 
    db_config$host, 
    ")(PORT=",
    db_config$port, 
    "))(CONNECT_DATA=(service_name=", 
    db_config$service_name, 
    ")))"
  )
  conn=ROracle::dbConnect(
    drv=DBI::dbDriver("Oracle"), 
    username=db_config$username, 
    password=db_config$password, 
    dbname=connect.string
  )
  file.remove(paste0(
    strsplit(config_filename,"[.]")[[1]][1],
    ".yml"
  ))
  return(conn)
}
